from __future__ import annotations

import json
from pathlib import Path

import pandas as pd
import streamlit as st

from app_utils.config import PROJECT_ROOT

PREDICTIONS_PATH = PROJECT_ROOT / "artifacts" / "model_predictions.csv"
METRICS_PATH = PROJECT_ROOT / "artifacts" / "model_metrics.json"


@st.cache_data(show_spinner="Loading model forecasts...", ttl="1h")
def load_model_predictions(
    path: Path = PREDICTIONS_PATH,
) -> pd.DataFrame:
    """Load row-level actual and predicted demand values."""
    if not path.exists():
        raise FileNotFoundError(
            f"Forecast artifact not found: {path}. "
            "Run `python scripts/run_model_pipeline.py` first."
        )

    df = pd.read_csv(path, parse_dates=["timestamp"])
    required_columns = {
        "timestamp",
        "store_id",
        "product_id",
        "actual_demand",
        "predicted_demand",
        "forecast_error",
    }
    missing = required_columns.difference(df.columns)
    if missing:
        missing_text = ", ".join(sorted(missing))
        raise ValueError(
            f"Forecast artifact is missing required columns: {missing_text}"
        )

    numeric_columns = [
        "actual_demand",
        "predicted_demand",
        "forecast_error",
    ]
    df[numeric_columns] = df[numeric_columns].apply(
        pd.to_numeric,
        errors="coerce",
    )

    return (
        df.dropna(
            subset=[
                "timestamp",
                "actual_demand",
                "predicted_demand",
            ]
        )
        .sort_values("timestamp")
        .reset_index(drop=True)
    )


@st.cache_data(show_spinner=False, ttl="1h")
def load_model_metrics(path: Path = METRICS_PATH) -> dict:
    """Load metrics generated by the reproducible model pipeline."""
    if not path.exists():
        raise FileNotFoundError(
            f"Metrics artifact not found: {path}. "
            "Run `python scripts/run_model_pipeline.py` first."
        )

    with path.open("r", encoding="utf-8") as file:
        return json.load(file)
